www/media/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns(
    '',
    url(r'^videos/$',
        views.YoutubeVideoListView.as_view(), name="youtube-list-view"),
    url(r'^galleries/$',
        views.FlickrAlbumListView.as_view(), name="flickr-list-view"),
    url(r'^press/$',
        views.PressListView.as_view(), name="press-list-view"),
    url(r'^tags/$',
        views.TagListView.as_view(), name='tag-list-view'),

    url(r'^videos/(?P<slug>[-_\w]+)/$',
        views.YoutubeEntryDetailView .as_view(), name='youtube-detail-view'),
    url(r'^galleries/(?P<slug>[-_\w]+)/$',
        views.FlickAlbumDetailView .as_view(), name='flickr-detail-view'),
    url(r'^press/(?P<slug>[-_\w]+)/$',
        views.PressDetailView .as_view(), name='press-detail-view'),
    url(r'^tags/(?P<slug>[-_\w]+)/$',
        views.TagDetailView.as_view(), name='tag-detail-view'),
)

www/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import patterns, include, url
from django.views import generic


admin.autodiscover()

urlpatterns = patterns(
    '',
    # external apps
    (r'^ckeditor/', include('ckeditor_uploader.urls')),
    (r'^s3direct/', include('s3direct.urls')),

    # prometheus urls
    (r'^admin/', include(admin.site.urls)),
    (r'^content/', include('media.urls', namespace='media')),
    (r'', include('content.urls')),
)

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    import debug_toolbar

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += patterns(
        '',
        url(r'^404/$', generic.TemplateView.as_view(
            template_name='404.html'), name="404"),
        url(r'^500/$', generic.TemplateView.as_view(
            template_name='500.html'), name="500"),
        url(r'^__debug__/', include(debug_toolbar.urls)))

www/templates/partials/flickr_embed.html
<div class="flickrWrapper">

{% if thumbnail %}
<a href="{{ object.get_absolute_url }}">
  <img class="image image-list" src="{{ object.flickr_thumbnail_url }}">
</a>

{% else %}

<div id="flickrembed_25"></div><script src='https://flickrembed.com/embed_v2.js.rand.php?container=flickrembed_25&source=flickr&layout=responsive&input={{object.flickr_album_url}}&sort=0&by=album&theme=default_notextpanel&scale=fit&speed=15000&limit=10&skin=default&autoplay=false'></script><script type="text/javascript">function showpics(){var a=$("#box").val();$.getJSON("http://api.flickr.com/services/feeds/photos_public.gne?tags="+a+"&tagmode=any&format=json&jsoncallback=?",function(a){$("#images").hide().html(a).fadeIn("fast"),$.each(a.items,function(a,e){$("<img/>").attr("src",e.media.m).appendTo("#images")})})}</script>

<a href="{{ object.flickr_album_url }}" class="social-icon-js" target="_blank" data-target="flickr-out" title="Flickr"><small>View on Flickr</small></a>
{% endif %}

</div>

www/templates/partials/footer.html
<div class="copyright">
    <p>&copy; farahVisualArts. All rights reserved. {% now "Y" %} | Farah Soobhan.</p>
</div>

www/templates/partials/google_analytics.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '{{ GA_TRACKING_CODE }}', 'auto');
  ga('send', 'pageview');

</script>

www/templates/partials/header.html
{% load static from staticfiles %}
<div class="header-wrapper">
    <div class="header" >
        <div class="logo">
            <img class="image-centered" src={% static "images/logo.png" %} alt="FVA logo">
            <span>&nbsp</span>
        </div>
        <div class="triangle-up"></div>
    </div>
</div>

www/templates/partials/menu.html
<div class="menu-wrapper">
		<div class="menu">
			<ul>
                <li><a href="{% url 'home' %}" accesskey="1" title="">Home</a></li>
                <li><a href="{% url 'biography' %}" accesskey="2" title="">Biography</a></li>
                <li><a href="{% url 'contact' %}" accesskey="3" title="">Contact</a></li>
                <li><a href="{% url 'media:youtube-list-view' %}" accesskey="4" title="">Videos</a></li>
                <li><a href="{% url 'media:flickr-list-view' %}" accesskey="5" title="">Gallery</a></li>
                <li><a href="{% url 'media:press-list-view' %}" accesskey="6" title="">Press</a></li>
			</ul>
		</div>
</div>

www/templates/partials/messages.html
{% if messages %}
    <ul class="messagelist">
        {% for message in messages %}
          <li {% if message.tags %}class="{{ message.tags }}"{% endif %}>
              <i class="icon fa-info-circle"></i>&nbsp; {{ message|capfirst }}
          </li>
        {% endfor %}
    </ul>
{% endif %}

www/templates/partials/social.html
{% load static from staticfiles %}
<div class="social">
    <div class="social-wrapper">
        <ul>
            <li>
            <a href="https://facebook.com/farahvisualarts/" class="social-icon-js" target="_blank" data-target="facebook" title="Facebook"><i class="icon fa-facebook"></i></a>
            </li>

            <li>
            <a href="https://instagram.com/farahvisualarts/" class="social-icon-js" target="_blank" data-target="instagram" title="Instagram"><i class="icon fa-instagram"></i></a>
            </li>

            <li>
            <a href="https://youtube.com/farahVisualArts" class="social-icon-js" target="_blank" data-target="youtube" title="YouTube"><i class="icon fa-youtube"></i></a>
            </li>

            <li>
            <a href="https://twitter.com/farahvisualarts" class="social-icon-js" target="_blank" data-target="twitter" title="Twitter"><i class="icon fa-twitter"></i></a>
            </li>
        </ul>
    </div>
</div>

www/templates/partials/youtube_embed.html
<div class="videoWrapper">
    <div id="player"></div>
</div>
<script>
    // 2. This code loads the IFrame Player API code asynchronously.
    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    // 3. This function creates an <iframe> (and YouTube player)
    //    after the API code downloads.
    var player;
    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            height: '390',
            width: '640',
            playerVars: {'autoplay': '0', 'color': 'white','theme':'dark' },
            videoId: '{{ youtube_id }}',
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
            }
        });
    }

    // 4. The API will call this function when the video player is ready.
    function onPlayerReady(event) {
        event.target.cueVideo();
    }

    // 5. The API calls this function when the player's state changes.
    //    The function indicates that when playing a video (state=1),
    //    the player should play for six seconds and then stop.
    var done = false;
    function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
            setTimeout(stopVideo, 6000);
            done = true;
        }
    }
    function stopVideo() {
        player.stopVideo();
    }
</script>